sd_options: # These options are for the SD Card Import
  sd_path: E:/ # What location/partition/volume is your CPAP Card?
  save_to_path: LatestCPAP # This is a subfolder of the location where the python files exist
  number_of_days: 2 # newest number of days to copy
  verbose: false # show extra logging
  test_only: false # does a "dry run" without copying any actual data

upload_options: # These options are for the upload to Sleep HQ
  client_id: Put Client ID value here # get this value from Sleep HQ API keys. See Readme.MD
  client_secret: Put Client  # get this value from Sleep HQ API keys. See Readme.MD
  data_path: LatestCPAP # This is  a subfolder of the location where the python files exist.
  verbose: false # show extra logging

